services:
   descier-app:
      build:
         context: .
         dockerfile: Dockerfile
      image: descier-app-image:${APP_VERSION:-latest}
      ports:
         - '${PORT:-3000}:3000'
      working_dir: /app
      command: npm start
      deploy:
         replicas: ${REPLICAS:-1}
         restart_policy:
            condition: on-failure
      pull_policy: never
      environment:
         NODE_ENV: ${NODE_ENV:-production}
         PORT: ${PORT:-3000}
      healthcheck:
         test: ['CMD', 'curl', '-f', 'http://localhost:3000/home']
         interval: 30s
         timeout: 10s
         retries: 3
      volumes:
         - ./logs:/app/logs
      networks:
         - descier-network

networks:
   descier-network:
      driver: bridge
