services:
   descier-app:
      build:
         context: .
         dockerfile: Dockerfile
      image: descier-app-image
      ports:
         - '80:80'
      working_dir: /app
      command: npm run start -p 80
      deploy:
         replicas: 1
         restart_policy:
            condition: on-failure
      pull_policy: never
      environment:
         NODE_ENV: production
