name: Build, Push Docker Image, and Deploy to ECS (Develop)

on:
   push:
      branches:
         - develop

jobs:
   build-and-deploy:
      if: github.ref == 'refs/heads/develop'
      name: CD deScier Front-End (Develop)
      runs-on: ubuntu-latest
      timeout-minutes: 6

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up QEMU
           uses: docker/setup-qemu-action@v2

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v2
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

         - name: Log in to Amazon ECR
           id: login-ecr
           uses: aws-actions/amazon-ecr-login@v2
           with:
              registry-type: private

         - name: List ECR repositories
           run: |
              echo "Listing all ECR repositories:"
                aws ecr describe-repositories --region "${{ secrets.AWS_REGION }}" --query 'repositories[*].repositoryName' --output table

         - name: Extract ECR repository URI
           id: ecr
           run: |
              echo "Attempting to describe ECR repository: ${{ secrets.ECR_REPOSITORY_DEV }}"
              if [ -z "${{ secrets.ECR_REPOSITORY_DEV }}" ]; then
                echo "Error: ECR_REPOSITORY_DEV secret is empty"
                exit 1
              fi
              uri=$(aws ecr describe-repositories --repository-names "${{ secrets.ECR_REPOSITORY_DEV }}" --region "${{ secrets.AWS_REGION }}" --query 'repositories[0].repositoryUri' --output text)
              if [ $? -ne 0 ]; then
                echo "Error: Failed to describe ECR repository"
                exit 1
              fi
              if [ -z "$uri" ]; then
                echo "Error: ECR repository URI is empty"
                exit 1
              fi
              echo "uri=$uri" >> $GITHUB_ENV
              echo "Extracted ECR URI: $uri"

         - name: Get Secrets from AWS Secrets Manager
           id: get-secrets
           run: |
              secret=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_MANAGER_SECRET_DEV }} --query SecretString --output text)
              echo "$secret" | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' > .env
              echo "ENV_FILE<<EOF" >> $GITHUB_ENV
              cat .env >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV

         - name: Debug .env file
           run: cat .env

         - name: Debug environment variables
           run: |
              echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
              echo "ECR_REPOSITORY_DEV: ${{ secrets.ECR_REPOSITORY_DEV }}"
              echo "uri: ${{ env.uri }}"

         - name: Build, Tag, and Push Docker image
           id: build-image
           run: |
              if [ -z "${{ env.uri }}" ]; then
                echo "Error: ECR URI is empty. Make sure the previous step to extract ECR repository URI was successful."
                exit 1
              fi
              # Get the short SHA of the commit
              SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
              # Build the image
              docker build --build-arg ENV_FILE="${{ env.ENV_FILE }}" -t ${{ env.uri }}:latest -t ${{ env.uri }}:$SHORT_SHA .
              # Push both tags
              docker push ${{ env.uri }}:latest
              docker push ${{ env.uri }}:$SHORT_SHA
              # Set the output to the tagged image
              echo "image=${{ env.uri }}:$SHORT_SHA" >> $GITHUB_OUTPUT

         - name: Download current ECS task definition
           id: download-task-def
           run: |
              aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_DEV }} --region ${{ secrets.AWS_REGION }} --query 'taskDefinition' > task-definition.json

         - name: Update image in ECS task definition
           id: update-task-def
           run: |
              jq --arg image "${{ steps.build-image.outputs.image }}" '.containerDefinitions[0].image = $image | del(.taskDefinitionArn, .revision, .status, .registeredAt, .registeredBy, .requiresAttributes, .compatibilities)' task-definition.json > updated-task-definition.json
         - name: Register new ECS task definition
           id: register-task-def
           run: |
              TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://updated-task-definition.json --region ${{ secrets.AWS_REGION }} --query 'taskDefinition.taskDefinitionArn' --output text)
              echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> $GITHUB_ENV

         - name: Deploy Amazon ECS task definition
           uses: aws-actions/amazon-ecs-deploy-task-definition@v2
           with:
              task-definition: updated-task-definition.json
              service: ${{ secrets.ECS_SERVICE_NAME_DEV }}
              cluster: ${{ secrets.ECS_CLUSTER_NAME_DEV }}

         - name: Log out of Amazon ECR
           run: |
              docker logout ${{ env.uri }}
