name: Continuous Deployment

on:
   push:
      branches:
         - feat/rafael/ci-cd-vps
         - main

jobs:
   deploy:
      name: Deploy to VPS
      runs-on: self-hosted
      steps:
         - name: Checkout Code
           uses: actions/checkout@v3
           with:
              fetch-depth: 0

         - name: Setup Node
           uses: actions/setup-node@v3
           with:
              node-version: 23

         - name: Check environment
           run: |
              echo "Sistema operacional: $(uname -a)"
              echo "Node.js version: $(node -v)"
              echo "NPM version: $(npm -v)"
              echo "Diretório atual: $(pwd)"

         - name: Pull Latest Code
           run: |
              git fetch --all
              git reset --hard origin/${{ github.ref_name }}
              git pull

         - name: Set .env
           run: |
              if [ -n "${{ secrets.ENV_PROD }}" ]; then
                echo "${{ secrets.ENV_PROD }}" > .env
              else
                echo "Erro: O segredo ENV_PROD não está configurado. Configure-o em Settings > Secrets and variables > Actions"
                exit 1
              fi

         - name: Install Dependencies
           run: npm install

         - name: Build Application
           run: npm run build

         - name: Ensure PM2 is installed
           run: |
              if ! command -v pm2 &> /dev/null; then
                npm install -g pm2
              fi

         - name: Kill processes in port 3000
           run: |
              if command -v lsof &> /dev/null; then
                sudo kill -9 $(sudo lsof -t -i:3000) || echo "No process to kill"
              else
                echo "lsof não encontrado, tentando alternativa..."
                sudo fuser -k 3000/tcp || echo "No process to kill"
              fi

         - name: Restart Application
           run: |
              pm2 delete "deScier Platform" || echo "No process to delete"
              pm2 start --name "deScier Platform" npm -- start

         - name: Save PM2 process list
           run: pm2 save

         - name: Notify deployment status
           run: |
              echo "Deployment concluído com sucesso para ${{ github.ref_name }} em $(date)"
