name: CI Pipeline (Pull Request)

on:
   pull_request:
      branches:
         - main
         - feat/rafael/ci-cd-vps

jobs:
   quality:
      name: Code Quality Check
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '23'

         - name: Install pnpm
           run: npm install -g pnpm

         - name: Install dependencies
           run: pnpm install --no-frozen-lockfile

         - name: Run lint checks
           run: pnpm run lint

         - name: Type check
           run: pnpm run typecheck || echo "Sem verificação de tipos configurada"

         - name: Build check
           run: pnpm run build
